repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.15.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
